### ISSUE TITLE
gen_server push_notification return {Timeout, StreamId}

### ISSUE THREAD

**Issue by turtleDeng** [inaka/apns4erl#182] opened 2017-06-07 09:29 UTC
```
-module(push_server).

-behaviour(gen_server).

-export([start_link/1]).

-export([init/1, handle_call/3, handle_cast/2, handle_info/2, terminate/2, code_change/3]).

-define(SERVER, ?MODULE).

-record(state, {}).

start_link(Name) ->
    gen_server:start_link({local, ?SERVER}, ?MODULE, [Name], []).

init([Name]) ->
    apns:connect(cert, Name),
    {ok, #state{}}.

handle_call(_Request, _From, State) ->
    io:format("handle call --~p~n", [_Request]),
    Reply = ok,
    {reply, Reply, State}.

handle_cast(_Msg, State) ->
    io:format("handle cast --~p~n", [_Msg]),
    {noreply, State}.

handle_info({apns_response, Server, StreamID, Response} = Info, State) ->
    io:format("handle info --~p~n", [Info]),
    {noreply, State}.

terminate(_Reason, _State) ->
    ok.

code_change(_OldVsn, State, _Extra) ->
        {ok, State}.
```
Where the client is a gen_server behaviour, the received message in handle_info, will not execute all
https://github.com/inaka/apns4erl/blob/master/src/apns_connection.erl#L217
https://github.com/inaka/apns4erl/blob/master/src/apns_connection.erl#L340

**Comment by ferigis** [comment] 2017-06-07 11:08
Hi @turtleDeng,
Where are you calling `apns:push_notification` in your code?

**Comment by turtleDeng** [comment] 2017-06-08 01:18
Erlang Terminal   calling apns:push_notification

**Comment by ferigis** [comment] 2017-06-08 01:21
@turtleDeng if you call `apns:pull_notification` from your erlang console is that process which could receive the `{apns_response, Server, StreamID, Response}` message.
Bottom line, the process which call `apns:pull_notification` will receive the message. So if you want to receive it on your gen server you must to call push_notification from that process

**Comment by ferigis** [comment] 2017-06-08 12:17
@turtleDeng I see what are you doing, actually I didn't test to connect from one process and push from other.
let me reproduce it on my local and I will let you know what is happening.

**Comment by ferigis** [comment] 2017-06-08 12:28
Hi @turtleDeng, I have tested your code.

```
9> apns:push_notification(my_connection, DeviceId, Notification).
06:24:33.752 [info] [client] Stream 1 WindowUpdate 28
handle info --{apns_response,<0.134.0>,1,
                             {400,
                              [{<<"apns-id">>,
                                <<"6220C397-27F4-DD76-4F5A-4C34E580D2F0">>}],
                              [{<<"reason">>,<<"TopicDisallowed">>}]}}
{timeout,1}
```
`apns4erl` was done thinking in one process should connect and push. We did it thinking in a pool of servers which could balance the load

**Comment by dcy** [comment] 2017-06-22 10:25
@ferigis Can ```apns:push_notification```  get the push result synchronously, not by handle_info asynchronous?

**Comment by dcy** [comment] 2017-06-22 10:35
https://github.com/inaka/apns4erl/blob/master/src/apns_connection.erl#L219
HTTP/2 can get the push result synchronously, but the latest version make it impossible.
And I can not use it with [turtle](https://github.com/shopgun/turtle)

**Comment by dcy** [comment] 2017-06-22 10:39
https://github.com/inaka/apns4erl/compare/master...dcy:fix1
Maybe something like this is better(not test), What's your opinion? @ferigis @elbrujohalcon

**Comment by ferigis** [comment] 2017-06-22 11:12
Hi @dcy. 
There is an issue in your code with the timeouts. 

https://github.com/inaka/apns4erl/compare/master...dcy:fix1#diff-659457922367adf5a4d889b7149f30c4R179

gen_server has a default timeout (I think it is 5 seconds), if your call to apns is greater than 5 seconds your conection will go down.

This is the way we found in order to use dynamic timeouts

**Comment by dcy** [comment] 2017-06-22 12:56
@ferigis https://github.com/dcy/apns4erl/blob/fix1/src/apns_connection.erl#L145 use infinity to change 5s defalut timeout.
And https://github.com/dcy/apns4erl/blob/fix1/src/apns_connection.erl#L195 here to use dynamic timeouts

**Comment by dcy** [comment] 2017-06-22 13:05
Before apns4erl 2.0, I think the most inconvenience of apns4erl is can not get the push response synchronously, Because the response say "BadDeviceToken", i don't know which device_token is bad. finally to 2.0, it can.
But 2.1.0, The most inconvienience is back.

**Comment by ferigis** [comment] 2017-06-22 13:33
@dcy 
`apns: push_notification/3,4` is synchronous. You must call it from the same process you opened the connection.
If you are getting an "BadDeviceToken" it is a response from APNS servers. 
You must check [HTTP/2 Response from APNs](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) there you can see all the possible responses from APNS. Regarding that, your "BadDeviceToken" means
```
The specified device token was bad. Verify that the request contains a valid token and that the token matches the environment.
```

**Comment by ferigis** [comment] 2017-06-22 14:16
@dcy 
We wrote an example for `Pushito` where we use it on a pool of connections. It is written in Elixir but It can be applied to `apns4erl` too, I am going to release a new version in hex in order to allow that but you can test with the master version if you want.

Check the example [here](https://github.com/inaka/pushito/tree/master/examples/push_pool)

**Comment by dcy** [comment] 2017-06-22 14:34
@ferigis Thanks! I think i get it why you design it like this(same process connect and push).
I already planed to use apns4erl with poolboy. Especially in China, it is slow to push apns.

**Comment by ferigis** [comment] 2017-06-22 14:36
@dcy great! I am pushing right now a new version (2.1.1) which allows creating connections without name. After that you can check the pushito example in order to use a pool but eventually we will write the same example but for apns4erl

**Comment by ferigis** [comment] 2017-06-22 14:45
@dcy the new version 2.1.1 is uploaded. You can fetch it from hex.pm too 

```
{apns, "2.1.1", {pkg, apns4erl}}
```
I am going to close this issue. If you need something else, please, open a new one

Thanks for use apns4erl!

**Closed** 2017-06-22 14:45 UTC

**Comment by boboxiaodd** [comment] 2017-06-24 07:02
@ferigis 
The notification is success recived, but retrun {timeout,x}
the config file:
```erlang
[
 {
   apns,
   [ {apple_host,       "api.push.apple.com"}
   , {apple_port,       443}
   , {certfile,         "priv/cert.pem"}
   , {keyfile,          "priv/key.pem"}
   , {token_keyfile,    "priv/APNsAuthKey_ES5MDTBU2G.p8"}
   , {timeout,          10000}

   %% APNs Headers

   , {apns_id,          undefined}
   , {apns_expiration,  0}
   , {apns_priority,    10}
   , {apns_topic,       "com.trident.lbschat.enterprise"}
   , {apns_collapse_id, undefined}

   %% Feedback
   , {feedback_host,    "feedback.push.apple.com"}
   , {feedback_port,    2195}
   ]
 },
 {sasl, [{sasl_error_logger, false}]}
].

```

**Comment by dcy** [comment] 2017-06-24 08:05
@boboxiaodd you should connect and push in the same process
